version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule: { interval: weekly, day: monday }
    open-pull-requests-limit: 10
    groups:
      dev-tooling:
        patterns: ['@types/*', 'eslint*', 'prettier*', 'typescript', 'vitest', 'turbo', '@vitest/*']
      nest:
        patterns: ['@nestjs/*']
      next:
        patterns: ['next', 'react', 'react-dom', '@types/react*']
    commit-message: { prefix: 'chore(deps)' }

  - package-ecosystem: github-actions
    directory: '/'
    schedule: { interval: weekly, day: monday }
    commit-message: { prefix: 'chore(ci)' }

  - package-ecosystem: docker
    directory: '/docker'
    schedule: { interval: weekly, day: monday }
    commit-message: { prefix: 'chore(docker)' }
