export default [
  'packages/taxonomy',
  'packages/contracts',
  'packages/provider-spi',
  'packages/adapter-kit',
  'packages/ledger',
  'packages/reconciliation',
  'packages/conformance',
  'packages/crypto',
  'packages/db',
  'packages/observability',
  'packages/adapters/*',
  'apps/api',
  'apps/worker',
  'apps/mock-bank',
  'e2e',
];
