export enum BaasErrorCategory {
  VALIDATION = 'VALIDATION',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BUSINESS_RULE = 'BUSINESS_RULE',
  COMPLIANCE = 'COMPLIANCE',
  PROVIDER = 'PROVIDER',
  RATE_LIMIT = 'RATE_LIMIT',
  INTERNAL = 'INTERNAL',
}

export enum BaasErrorCode {
  // VALIDATION
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_TAX_ID = 'INVALID_TAX_ID',
  INVALID_PIX_KEY = 'INVALID_PIX_KEY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_EMV_PAYLOAD = 'INVALID_EMV_PAYLOAD',
  INVALID_END_TO_END_ID = 'INVALID_END_TO_END_ID',
  INVALID_CURSOR = 'INVALID_CURSOR',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  MISSING_IDEMPOTENCY_KEY = 'MISSING_IDEMPOTENCY_KEY',

  // AUTHENTICATION / AUTHORIZATION
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  INVALID_API_KEY = 'INVALID_API_KEY',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  SIGNATURE_INVALID = 'SIGNATURE_INVALID',
  SIGNATURE_EXPIRED = 'SIGNATURE_EXPIRED',
  NONCE_REPLAYED = 'NONCE_REPLAYED',
  /** Sessao do console expirada ou revogada. Distinta de credencial errada. */
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  /**
   * Senha correta, segundo fator ausente.
   *
   * Separado de AUTHENTICATION_FAILED de proposito: a acao do cliente e
   * pedir o codigo TOTP, nao pedir a senha de novo. Fundir os dois obrigaria
   * o console a casar a mensagem por string.
   */
  MFA_REQUIRED = 'MFA_REQUIRED',
  AUTHORIZATION_DENIED = 'AUTHORIZATION_DENIED',
  INSUFFICIENT_SCOPE = 'INSUFFICIENT_SCOPE',
  /** A API key pertence a outro ambiente que o recurso alvo. */
  ENVIRONMENT_MISMATCH = 'ENVIRONMENT_MISMATCH',

  // NOT FOUND
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  /** Chave inexistente no DICT. */
  PIX_KEY_NOT_FOUND = 'PIX_KEY_NOT_FOUND',
  CHARGE_NOT_FOUND = 'CHARGE_NOT_FOUND',
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',

  // CONFLICT
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  PIX_KEY_ALREADY_EXISTS = 'PIX_KEY_ALREADY_EXISTS',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENT_REQUEST_IN_PROGRESS = 'IDEMPOTENT_REQUEST_IN_PROGRESS',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  CONCURRENT_MODIFICATION = 'CONCURRENT_MODIFICATION',

  // BUSINESS RULE
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  ACCOUNT_NOT_ACTIVE = 'ACCOUNT_NOT_ACTIVE',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
  OUTSIDE_OPERATING_HOURS = 'OUTSIDE_OPERATING_HOURS',
  CHARGE_EXPIRED = 'CHARGE_EXPIRED',
  CHARGE_ALREADY_PAID = 'CHARGE_ALREADY_PAID',
  REFUND_WINDOW_EXPIRED = 'REFUND_WINDOW_EXPIRED',
  REFUND_AMOUNT_EXCEEDS_ORIGINAL = 'REFUND_AMOUNT_EXCEEDS_ORIGINAL',
  TRANSACTION_NOT_REVERSIBLE = 'TRANSACTION_NOT_REVERSIBLE',
  SELF_TRANSFER_NOT_ALLOWED = 'SELF_TRANSFER_NOT_ALLOWED',
  LEDGER_UNBALANCED = 'LEDGER_UNBALANCED',

  // COMPLIANCE
  ONBOARDING_REQUIRED = 'ONBOARDING_REQUIRED',
  ONBOARDING_PENDING = 'ONBOARDING_PENDING',
  COMPLIANCE_REJECTED = 'COMPLIANCE_REJECTED',
  SANCTIONS_BLOCK = 'SANCTIONS_BLOCK',
  DOCUMENT_REQUIRED = 'DOCUMENT_REQUIRED',

  // PROVIDER
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  PROVIDER_TIMEOUT = 'PROVIDER_TIMEOUT',
  PROVIDER_RATE_LIMITED = 'PROVIDER_RATE_LIMITED',
  /**
   * O provedor recusou a operacao. E TAMBEM o fallback da tabela de
   * mapeamento de cada adapter — por isso a suite de conformidade reprova uma
   * fixture de erro que caia aqui: significa que o codigo do provedor nao foi
   * mapeado.
   */
  PROVIDER_REJECTED = 'PROVIDER_REJECTED',
  /**
   * O servidor do provedor falhou (5xx que nao e indisponibilidade).
   *
   * Distinto de PROVIDER_REJECTED: ali houve decisao, aqui houve defeito.
   * `safeToRetry: false` porque um 500 numa escrita pode ter acontecido DEPOIS
   * de o efeito ser aplicado do lado deles.
   */
  PROVIDER_INTERNAL_ERROR = 'PROVIDER_INTERNAL_ERROR',
  /** A resposta do provedor nao passou no nosso schema. */
  PROVIDER_CONTRACT_VIOLATION = 'PROVIDER_CONTRACT_VIOLATION',
  PROVIDER_CREDENTIALS_INVALID = 'PROVIDER_CREDENTIALS_INVALID',
  PROVIDER_CIRCUIT_OPEN = 'PROVIDER_CIRCUIT_OPEN',
  /** Timeout numa escrita: nao sabemos se o efeito ocorreu. Nunca retentar. */
  PROVIDER_OUTCOME_UNKNOWN = 'PROVIDER_OUTCOME_UNKNOWN',
  CAPABILITY_NOT_SUPPORTED = 'CAPABILITY_NOT_SUPPORTED',
  CAPABILITY_CONSTRAINT_VIOLATED = 'CAPABILITY_CONSTRAINT_VIOLATED',

  // OUTROS
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}

interface CodeMeta {
  category: BaasErrorCategory;
  httpStatus: number;
  retryable: boolean;
  /**
   * Seguro retentar uma escrita que move dinheiro. Distinto de `retryable`:
   * um timeout num GET e ambos; num POST /pix/transfers so e seguro porque
   * mandamos idempotency key ao provedor.
   */
  safeToRetry: boolean;
}

const V = BaasErrorCategory;
const meta = (
  category: BaasErrorCategory,
  httpStatus: number,
  retryable = false,
  safeToRetry = retryable,
): CodeMeta => ({ category, httpStatus, retryable, safeToRetry });

export const ERROR_CODE_META: Readonly<Record<BaasErrorCode, CodeMeta>> = Object.freeze({
  [BaasErrorCode.VALIDATION_ERROR]: meta(V.VALIDATION, 422),
  [BaasErrorCode.MISSING_REQUIRED_FIELD]: meta(V.VALIDATION, 422),
  [BaasErrorCode.INVALID_TAX_ID]: meta(V.VALIDATION, 422),
  [BaasErrorCode.INVALID_PIX_KEY]: meta(V.VALIDATION, 422),
  [BaasErrorCode.INVALID_AMOUNT]: meta(V.VALIDATION, 422),
  [BaasErrorCode.INVALID_EMV_PAYLOAD]: meta(V.VALIDATION, 422),
  [BaasErrorCode.INVALID_END_TO_END_ID]: meta(V.VALIDATION, 422),
  [BaasErrorCode.INVALID_CURSOR]: meta(V.VALIDATION, 400),
  [BaasErrorCode.CURRENCY_MISMATCH]: meta(V.VALIDATION, 422),
  [BaasErrorCode.MISSING_IDEMPOTENCY_KEY]: meta(V.VALIDATION, 400),

  [BaasErrorCode.AUTHENTICATION_FAILED]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.INVALID_API_KEY]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.API_KEY_REVOKED]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.SIGNATURE_INVALID]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.SIGNATURE_EXPIRED]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.NONCE_REPLAYED]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.SESSION_EXPIRED]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.MFA_REQUIRED]: meta(V.AUTHENTICATION, 401),
  [BaasErrorCode.AUTHORIZATION_DENIED]: meta(V.AUTHORIZATION, 403),
  [BaasErrorCode.INSUFFICIENT_SCOPE]: meta(V.AUTHORIZATION, 403),
  [BaasErrorCode.ENVIRONMENT_MISMATCH]: meta(V.AUTHORIZATION, 403),

  [BaasErrorCode.RESOURCE_NOT_FOUND]: meta(V.NOT_FOUND, 404),
  [BaasErrorCode.ACCOUNT_NOT_FOUND]: meta(V.NOT_FOUND, 404),
  [BaasErrorCode.TRANSACTION_NOT_FOUND]: meta(V.NOT_FOUND, 404),
  [BaasErrorCode.PIX_KEY_NOT_FOUND]: meta(V.NOT_FOUND, 404),
  [BaasErrorCode.CHARGE_NOT_FOUND]: meta(V.NOT_FOUND, 404),
  [BaasErrorCode.CONNECTION_NOT_FOUND]: meta(V.NOT_FOUND, 404),
  [BaasErrorCode.PROVIDER_NOT_FOUND]: meta(V.NOT_FOUND, 404),

  [BaasErrorCode.RESOURCE_ALREADY_EXISTS]: meta(V.CONFLICT, 409),
  [BaasErrorCode.PIX_KEY_ALREADY_EXISTS]: meta(V.CONFLICT, 409),
  [BaasErrorCode.IDEMPOTENCY_KEY_REUSED]: meta(V.CONFLICT, 422),
  [BaasErrorCode.IDEMPOTENT_REQUEST_IN_PROGRESS]: meta(V.CONFLICT, 409, true, true),
  [BaasErrorCode.INVALID_STATE_TRANSITION]: meta(V.CONFLICT, 409),
  [BaasErrorCode.CONCURRENT_MODIFICATION]: meta(V.CONFLICT, 409, true, true),

  [BaasErrorCode.INSUFFICIENT_FUNDS]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.ACCOUNT_NOT_ACTIVE]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.ACCOUNT_BLOCKED]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.LIMIT_EXCEEDED]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.OUTSIDE_OPERATING_HOURS]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.CHARGE_EXPIRED]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.CHARGE_ALREADY_PAID]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.REFUND_WINDOW_EXPIRED]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.REFUND_AMOUNT_EXCEEDS_ORIGINAL]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.TRANSACTION_NOT_REVERSIBLE]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.SELF_TRANSFER_NOT_ALLOWED]: meta(V.BUSINESS_RULE, 422),
  [BaasErrorCode.LEDGER_UNBALANCED]: meta(V.INTERNAL, 500),

  [BaasErrorCode.ONBOARDING_REQUIRED]: meta(V.COMPLIANCE, 422),
  [BaasErrorCode.ONBOARDING_PENDING]: meta(V.COMPLIANCE, 422),
  [BaasErrorCode.COMPLIANCE_REJECTED]: meta(V.COMPLIANCE, 422),
  [BaasErrorCode.SANCTIONS_BLOCK]: meta(V.COMPLIANCE, 403),
  [BaasErrorCode.DOCUMENT_REQUIRED]: meta(V.COMPLIANCE, 422),

  [BaasErrorCode.PROVIDER_UNAVAILABLE]: meta(V.PROVIDER, 503, true, true),
  [BaasErrorCode.PROVIDER_INTERNAL_ERROR]: meta(V.PROVIDER, 502, false, false),
  [BaasErrorCode.PROVIDER_TIMEOUT]: meta(V.PROVIDER, 504, true, false),
  [BaasErrorCode.PROVIDER_RATE_LIMITED]: meta(V.PROVIDER, 503, true, true),
  [BaasErrorCode.PROVIDER_REJECTED]: meta(V.PROVIDER, 502),
  [BaasErrorCode.PROVIDER_CONTRACT_VIOLATION]: meta(V.PROVIDER, 502),
  [BaasErrorCode.PROVIDER_CREDENTIALS_INVALID]: meta(V.PROVIDER, 502),
  [BaasErrorCode.PROVIDER_CIRCUIT_OPEN]: meta(V.PROVIDER, 503, true, true),
  // 202: nunca 5xx. Um 5xx convida o cliente a retentar, que e exatamente o
  // que precisamos evitar quando o pagamento pode ter sido aceito.
  [BaasErrorCode.PROVIDER_OUTCOME_UNKNOWN]: meta(V.PROVIDER, 202, false, false),
  [BaasErrorCode.CAPABILITY_NOT_SUPPORTED]: meta(V.PROVIDER, 501),
  [BaasErrorCode.CAPABILITY_CONSTRAINT_VIOLATED]: meta(V.VALIDATION, 422),

  [BaasErrorCode.RATE_LIMITED]: meta(V.RATE_LIMIT, 429, true, true),
  [BaasErrorCode.INTERNAL_ERROR]: meta(V.INTERNAL, 500, true, false),
  [BaasErrorCode.NOT_IMPLEMENTED]: meta(V.INTERNAL, 501),
});
