import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Barra lateral EXPLICITA, e nao `autogenerated`.
 *
 * A ordem em que alguem le esta documentacao e uma decisao editorial: o
 * modelo de dinheiro antes das rotas, a taxonomia antes dos adapters, os
 * fluxos antes do deploy. `autogenerated` ordenaria por nome de arquivo e
 * perderia isso na primeira pagina nova.
 */
const sidebars: SidebarsConfig = {
  principal: [
    'index',
    {
      type: 'category',
      label: 'Conceitos',
      collapsed: false,
      items: ['taxonomy/money', 'taxonomy/identifiers', 'taxonomy/status', 'taxonomy/errors'],
    },
    {
      type: 'category',
      label: 'Guias',
      items: [
        'guides/local-development',
        'guides/money-flows',
        'guides/writing-a-provider-adapter',
        'guides/recording-fixtures',
      ],
    },
    {
      type: 'category',
      label: 'Provedores',
      items: [
        'providers/capability-matrix',
        'providers/mock-bank',
        'providers/celcoin',
        'providers/asaas',
        'providers/woovi',
        'providers/dock',
        'providers/qitech',
      ],
    },
    {
      type: 'category',
      label: 'Decisoes de arquitetura',
      link: { type: 'doc', id: 'adr/index' },
      items: [{ type: 'autogenerated', dirName: 'adr' }],
    },
  ],
};

export default sidebars;
